# Extracts <g id="X"> blocks and their <path d="..."/> from face.svg + back.svg
# Generates app/seance/_components/body-svg/paths.ts

$svgDir = 'C:\Users\yassi\Desktop\tcp\t-aspriscombien\app\seance\_components\body-svg'
$outFile = "$svgDir\paths.ts"

# IDs that map to a muscle group (anything else like body, jointradial, hover, etc. is treated separately)
$muscleIds = @(
  'chest','front-shoulders','traps','biceps','forearms','abdominals','obliques','quads','calves',
  'rear-shoulders','traps-middle','lats','lowerback','triceps','glutes','hamstrings'
)
$outlineId = 'body'

function Extract-Groups([string]$svgText) {
  # Match <g ...id="..." ...>...</g> non-greedy — id may appear after other attrs (class, etc.)
  $rx = [regex]'<g\b[^>]*?\bid="([a-z\-]+)"[^>]*>(.*?)</g>'
  $matches = $rx.Matches($svgText)
  $result = @{}
  foreach ($m in $matches) {
    $id = $m.Groups[1].Value
    $inner = $m.Groups[2].Value
    if (-not $result.ContainsKey($id)) { $result[$id] = @() }
    # Extract all <path d="..."/>
    $pathRx = [regex]'<path[^>]*?\bd="([^"]+)"'
    foreach ($pm in $pathRx.Matches($inner)) {
      $result[$id] += $pm.Groups[1].Value
    }
  }
  return $result
}

$faceSvg = [System.IO.File]::ReadAllText("$svgDir\face.svg")
$backSvg = [System.IO.File]::ReadAllText("$svgDir\back.svg")

$faceGroups = Extract-Groups $faceSvg
$backGroups = Extract-Groups $backSvg

function Emit-Record([hashtable]$groups, [string]$varName) {
  $lines = @()
  $lines += "export const $varName`: Record<string, readonly string[]> = {"
  foreach ($id in $muscleIds) {
    if ($groups.ContainsKey($id) -and $groups[$id].Count -gt 0) {
      $paths = $groups[$id] | ForEach-Object { "    '" + ($_ -replace "'", "\'") + "'" }
      $joined = $paths -join ",`r`n"
      $lines += "  '$id': ["
      $lines += $joined
      $lines += "  ],"
    }
  }
  $lines += "}"
  return ($lines -join "`r`n")
}

function Emit-Outline([hashtable]$groups, [string]$varName) {
  $lines = @()
  $lines += "export const $varName`: readonly string[] = ["
  if ($groups.ContainsKey($outlineId)) {
    foreach ($p in $groups[$outlineId]) {
      $lines += "  '" + ($p -replace "'", "\'") + "',"
    }
  }
  $lines += "]"
  return ($lines -join "`r`n")
}

$header = @"
// AUTO-GENERATED by scripts/extract-body-paths.ps1
// Source: app/seance/_components/body-svg/{face,back}.svg (MuscleWiki anatomy)
// Re-run the script after editing the SVG files.

export const BODY_VIEWBOX = '0 0 660.46 1206.46'
"@

$faceRecord = Emit-Record $faceGroups 'FACE_GROUPS'
$backRecord = Emit-Record $backGroups 'BACK_GROUPS'
$faceOutline = Emit-Outline $faceGroups 'FACE_OUTLINE_PATHS'
$backOutline = Emit-Outline $backGroups 'BACK_OUTLINE_PATHS'

$full = "$header`r`n`r`n$faceRecord`r`n`r`n$backRecord`r`n`r`n$faceOutline`r`n`r`n$backOutline`r`n"
$utf8 = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outFile, $full, $utf8)
"OK: $($full.Length) chars"
"FACE keys: $($faceGroups.Keys -join ', ')"
"BACK keys: $($backGroups.Keys -join ', ')"
